### ISSUE TITLE
Example Code DPC for DE

### ISSUE THREAD

**Issue by abadgerw** [Mengbo-Li/protDP#1]
Thank you for a great package and associated paper. 

I was wondering if you had example code on how to use the DPC as part of a DE model as you did in your comparative analysis?

On a related note, how does DPC differ from proDA? https://github.com/const-ae/proDA

**Comment by Mengbo-Li** [comment]
Hi there thank you for the question and yes we are working on finalising the DPC-based pipeline for limma, which will be public soon via Bioconductor. 
Conceptually, the main difference is that our DPC models the missingness patterns as a standalone method, where the DPC can be used to guide many different other downstream analyses, not just DE. 
In proDA I believe the missingness modelling is integrated into the DE testing.

**Comment by abadgerw** [comment]
@Mengbo-Li Hope you are doing well. I just wanted to see if you had an update related to when this would be implemented into LIMMA? I would love to try it out with a current proteomics dataset I have on hand.
