### ISSUE TITLE
LIMMA Update with DPC Modeling

### ISSUE THREAD

**Issue by abadgerw** [Mengbo-Li/protDP#2]
@Mengbo-Li @gksmyth Hope you are doing well! I just wanted to see if you had an update related to when the DPC modeling would be implemented into LIMMA for use? I would love to try it out with a current proteomics dataset I have on hand.

**Comment by abadgerw** [comment]
@Mengbo-Li @gksmyth I just wanted to circle back and see if you had some insight into this query as I'd love to be able to use your fantastic tool?

**Comment by Mengbo-Li** [comment]
Hi there, 

We are developing a new package that will be submitted to Bioconductor and will interface between protDP and limma. Our hope is for that to be part of the Bioconductor 3.22 release in April 2025. 

Regards
Mengbo
